services:
  - type: web
    name: telegram-bot
    runtime: docker
    env: python
    build:
      dockerfile: Dockerfile
    envVars:
      - key: TOKEN
        value: 7336372322:AAEtIUcY6nNEEGZzIMjJdfYMTAMsLpTSpzk  # استبدل برمز البوت الخاص بك
    plan: free  # يمكنك تغيير الخطة إلى "starter" أو "standard" إذا كنت بحاجة إلى موارد أكبر